### ISSUE TITLE
Backbutton in Setting Page not working

### ISSUE THREAD

**Issue by iAlanx3** [aura-cz2006/aura-app#26]
Page: Setting

Issue: After tapping on "Change Home Address" button, the "App Bar Back" button no longer works.

Current Flow:
Settings->Change Home Address -> Submit or Back to Settings -> Unable to return from Settings to previous page.
How it should be like:
Settings->Change Home Address -> Submit or Back to Settings -> From Settings to Previous page.

**Comment by RealDyllon** [comment]
@jamiegoh would you mind moving this to jira?

**Comment by RealDyllon** [comment]
Fixed in a previous PR. Closing.
